# Generated by Django 5.2.14 on 2026-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authority', models.CharField(max_length=150)),
                ('date_earned', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('Experience', 'Professional Experience / Internship'), ('Education', 'Education')], default='Experience', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Dev', 'Web Development'), ('Data Science', 'Data Science & ML'), ('AI/NLP', 'AI & NLP'), ('Deep Learning', 'Deep Learning & CV'), ('Game Dev', 'Game Development'), ('Forecasting', 'Time Series Forecasting')], default='Web Dev', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Languages', 'Programming Languages'), ('Frameworks', 'Frameworks & Libraries'), ('Web', 'Web Technologies'), ('DevOps', 'DevOps & Tools'), ('Databases', 'Databases'), ('Concepts', 'Concepts')], default='Languages', max_length=50),
        ),
    ]
