# Generated by Django 5.2.14 on 2026-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_certification_timelineitem_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True),
        ),
    ]
